# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

require 'gettext/utils'

desc "Update pot/po files."
task :updatepo do
  GetText.update_pofiles("mozshot",
                         Dir.glob("{app,config,components,lib}/**/*.{rb,rhtml}"),
                         "mozshot 1.0.0")
end

desc "Create mo-files"
task :makemo do
  GetText.create_mofiles(true, "po", "locale")
end
