#!/bin/bash -e

displayno=51
num_server=4

#ulimit -c unlimited
ulimit -v 512000
unset XAUTHORITY

####

cd `dirname $0`/..

i=0
while [ "$i" -lt "$num_server" ]; do
  screen_opt="$screen_opt -screen $i 2048x2048x16"
  i=$((i+1))
done

Xvfb :$displayno -nolisten tcp $screen_opt > /dev/null &
bash -c 'while :; do ./ts.rb; done'&

i=0
while [ "$i" -lt "$num_server" ]; do
  DISPLAY=":${displayno}.${i}" nice -n 5 examples/run-mozshot &
  i=$((i+1))
done
